### ISSUE TITLE
unresolved reference to `getmail.spec` in `setup.py`

### ISSUE THREAD

**Issue by Kr1ss-XD** [rpuntaie/getmail#1]
Hey, thx a lot for porting this to Python 3, well done !

During my attempts to package this for the AUR, I noticed that you removed the `getmail.spec` file (which actually seems to be used for rpm packaging, not sure though). However, I guess you forgot to remove the reference to that file in `setup.py`, causing the build process to bail out.

FWIW, this file is also referenced in `MANIFEST.in`, which is likely just an aesthetic issue though.

 I have pushed a [-git package](https://aur.archlinux.org/packages/getmail-python3-git/) btw, where those references are removed in the `prepare()` function, and `mailwizard{,-git}` now depend on this new package. :)

**Comment by rpuntaie** [comment]
I removed the file references.

It was in `getmail-5.14.tar.gz`.
The file belongs into the according distros, though.
