### ISSUE TITLE
Issue with procmail

### ISSUE THREAD

**Issue by jborme** [rpuntaie/getmail#4]
I have been trying getmail 6 as a drop-in replacement for getmail 5.14, installing with python 3.7.7. I get an error when passing to procmail.

```
[destination]
type = MDA_external
path = /usr/bin/procmail
arguments = ("-f", "%(sender)", "-m", "~/.procmail/config.rc")
```

I send myself a simple plain text email and try to get it. (email address redacted)

```
Delivery error (command procmail 3177 error (127, exec of command procmail failed (replace() argument 2 must be str, not bytes)))
  msg 621/621 (33354 bytes) from <example@example.com>, delivery error (command procmail 3177 error (127, exec of command procmail failed (replace() argument 2 must be str, not bytes)))
  1 messages (33354 bytes) retrieved, 620 skipped
```
The message is actually not retrieved (procmail does not log any activity) and getmail does not mark it as seen. If I remove reference to procmail and deliver directly to the Maildir, it gets delivered.

**Comment by rpuntaie** [comment]
To make it easier for me to set up a the getmail procmail problem, could you post a minimal procmail and getmail config?

**Comment by rpuntaie** [comment]
The bug was due to the porting to Python 3.
Thanks for reporting.

The following test setup produced the error.

~/.local/etc/procmail/puntaier.roland@gmail.com

``` 
MAILDIR=$HOME/Mail/puntaier.roland@gmail.com
DEFAULT=$MAILDIR/INBOX
#LOGFILE=$HOME/.procmaillog
#VERBOSE=yes

:0
* ^Subject:.*test.*
tests/

:0
$DEFAULT/

```

/home/roland/.local/etc/getmail/puntaier.roland@gmail.com

```
[retriever]
type = SimpleIMAPSSLRetriever
server = imap.gmail.com
username = puntaier.roland@gmail.com
port = 993
password_command = ("pass", "gmail/puntaier.roland@gmail.com")

[destination]
type = MDA_external
path = /usr/bin/procmail
arguments = ("-f", "%(sender)", "-m", "/home/roland/.local/etc/procmail/puntaier.roland@gmail.com")

# instead of
#[destination]
#type = Maildir
#path = /home/roland/Mail/puntaier.roland@gmail.com/INBOX/

[options]
read_all = true
delete = true
```

Command:

```
getmail --rcfile=puntaier.roland@gmail.com --getmaildir=/home/roland/.local/etc/getmail

```

**Comment by jborme** [comment]
Thanks for your time and sorry I was not available earlier to provide the configuration files. The correction solved the problem at my place.
